name: drl
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.1.0
  - asn1crypto=1.3.0
  - backcall=0.1.0
  - blas=1.0
  - blinker=1.4
  - c-ares=1.15.0
  - ca-certificates=2020.1.1
  - cachetools=3.1.1
  - certifi=2019.11.28
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.0
  - cryptography=2.8
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cupti=10.1.168
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.10.1
  - dbus=1.13.6
  - decorator=4.4.1
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.56.2
  - google-auth=1.11.2
  - google-auth-oauthlib=0.4.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.4
  - icu=58.2
  - idna=2.8
  - imageio=2.6.1
  - intel-openmp=2019.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - jedi=0.16.0
  - jpeg=9b
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.11.4
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - markdown=3.1.1
  - matplotlib=3.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - ncurses=6.1
  - networkx=2.4
  - numpy=1.17.2
  - numpy-base=1.17.2
  - oauthlib=3.1.0
  - olefile=0.46
  - openssl=1.1.1d
  - opt_einsum=3.1.0
  - pandas=0.25.3
  - parso=0.6.1
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=19.2.3
  - plotly=4.3.0
  - prompt_toolkit=3.0.3
  - ptyprocess=0.6.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.19
  - pygments=2.5.2
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.6.9
  - python-dateutil=2.8.0
  - pytz=2019.3
  - pywavelets=1.1.1
  - qt=5.9.7
  - readline=7.0
  - requests=2.22.0
  - requests-oauthlib=1.3.0
  - retrying=1.3.3
  - rsa=4.0
  - scikit-image=0.16.2
  - setuptools=41.4.0
  - sip=4.19.8
  - sqlite=3.30.0
  - tensorboard=2.1.0
  - tensorflow=2.1.0
  - tensorflow-base=2.1.0
  - tensorflow-estimator=2.1.0
  - tensorflow-gpu=2.1.0
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=6.0.3
  - traitlets=4.3.3
  - urllib3=1.25.8
  - wcwidth=0.1.8
  - wheel=0.33.6
  - wrapt=1.11.2
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.8.1
    - alembic==1.4.1
    - astor==0.8.0
    - astroid==2.3.1
    - atari-py==0.2.6
    - box2d-py==2.3.8
    - cloudpickle==1.2.2
    - configparser==4.0.2
    - databricks-cli==0.9.1
    - docker==4.2.0
    - entrypoints==0.3
    - flask==1.1.1
    - future==0.18.0
    - gast==0.2.2
    - gitdb==4.0.2
    - gitpython==3.1.0
    - google-pasta==0.1.7
    - gorilla==0.3.0
    - grpcio==1.24.1
    - gunicorn==20.0.4
    - gym==0.14.0
    - isort==4.3.21
    - itsdangerous==1.1.0
    - jinja2==2.11.1
    - lazy-object-proxy==1.4.2
    - mako==1.1.2
    - markupsafe==1.1.1
    - mccabe==0.6.1
    - mlflow==1.7.2
    - prometheus-client==0.7.1
    - prometheus-flask-exporter==0.13.0
    - protobuf==3.10.0
    - pyglet==1.3.2
    - pylint==2.4.2
    - python-editor==1.0.4
    - pyyaml==5.3.1
    - querystring-parser==1.2.4
    - scipy==1.3.1
    - simplejson==3.17.0
    - six==1.12.0
    - smmap==3.0.1
    - sqlalchemy==1.3.13
    - sqlparse==0.3.1
    - tabulate==0.8.6
    - termcolor==1.1.0
    - typed-ast==1.4.0
    - websocket-client==0.57.0
    - werkzeug==0.16.0

